//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSTEntities : DbContext
    {
        public SMSTEntities()
            : base("name=SMSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Teacher> tbl_Teacher { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_Grade> tbl_Grade { get; set; }
        public virtual DbSet<tbl_Student> tbl_Student { get; set; }
        public virtual DbSet<tbl_Absence> tbl_Absence { get; set; }
        public virtual DbSet<tbl_Fees> tbl_Fees { get; set; }
    }
}
