//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Fees
    {
        [Display(Name = "Invoice ID")]
        public int InvoiceID { get; set; }

        [Display(Name = "Date of Payment")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public Nullable<System.DateTime> PaymentDate { get; set; }

        [Required]
        [Display(Name = "Student ID")]
        public Nullable<int> StudentID { get; set; }

        [Required]
        [Display(Name = "Grade ID")]
        public Nullable<int> GradeID { get; set; }

        [Required]
        [Display(Name = "Fees Paid")]
        public Nullable<double> Paid { get; set; }

        [Display(Name = "Fees Pending")]
        public Nullable<double> Pending { get; set; }

        [Required]
        [Display(Name = "Total Fees")]
        public Nullable<double> Total { get; set; }
    
        public virtual tbl_Grade tbl_Grade { get; set; }
        public virtual tbl_Student tbl_Student { get; set; }
    }
}
